apiVersion: v1
kind: Service
metadata:
  name: be-service
  labels:
    name: be-service
    app: BC15-GC
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: be-pod
    app: BC15-GC
