apiVersion: v1
kind: Service
metadata:
  name: fe-service
  labels:
    name: fe-service
    app: BC15-GC
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30004
  selector:
    name: fe-pod
    app: BC15-GC 
