apiVersion: v1
kind: Pod
metadata:
  name: be-pod
  labels:
    name: be-pod
    app: BC15-GC
spec:
  containers:
    - name: be
      image: dhanrajnath/bel
      ports:
        - containerPort: 8080
      env:
        - name: "SPRING_DATASOURCE_URL"
          value: "jdbc:postgresql://postgres:5432/jobs"
        - name: "SPRING_DATASOURCE_USERNAME"
          value: "postgres"
        - name: "SPRING_DATASOURCE_PASSWORD"
          value: "1234"
        - name: "SPRING_JPA_HIBERNATE_DDL_AUTO"
          value: "update"
