apiVersion: v1
kind: Pod
metadata:
  name: fe-pod
  labels:
    name: fe-pod
    app: BC15-GC
spec:
  containers:
    - name: fe
      image: dhanrajnath/fel
      ports:
        - containerPort: 3000
