apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: BC15-GC
spec:
  containers:
    - name: postgres
      image: dhanrajnath/postgres
      ports:
        - containerPort: 5432
      env:
        - name: "POSTGRES_USER"
          value: "postgres"
        - name: "POSTGRES_PASSWORD"
          value: "1234" 
        - name: "POSTGRES_DB"
          value: "jobs"
